# Numpy 주요 기능

### 객체

In [1]:
import numpy as np

In [2]:
# array의 경우에는 동질의 데이터를 다룰 수 있는 구조로 리스트 보다 빠름
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [3]:
# 생성할 때 데이터 타입을 지정 가능
np.array([1,2,3,4], dtype=np.float)

array([1., 2., 3., 4.])

In [4]:
# list comprebension 루프
np.array([range(i,i+3) for i in [1,4,7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 초기화 함수

In [5]:
# zeros ==> 배열을 0으로 채워 만들기(1차원 길이 10 형태)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# ones ==> 배열에 1로 채워 만들기(2차원 (3,5)형태)
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# full ==> 배열에 임의의 값으로 채워 만들기(2차원 (2,3)형태에 5로 채우기)
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [8]:
# arange ==> 배열에 수열의 값으로 채워 만들기([0~10)까지 2단계씩 채우기)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
# linspace ==> 배열에 균등하게 interval한 값으로 채워 만들기(0~100까지 5등분으로 정수값)
np.linspace(0,100,5,dtype=int)

array([  0,  25,  50,  75, 100])

### 난수 함수

In [10]:
# random ==> 배열을 0~1 사이의 임의의 값으로((3,3)형태)
np.random.random((3,3))

array([[0.95442396, 0.26114631, 0.36441701],
       [0.03188962, 0.17435203, 0.41400626],
       [0.00639169, 0.04209407, 0.00890156]])

In [11]:
# randint ==> 배열을 [0~10)범위의 정수값으로([0,10)값을 (3,3)형태)
np.random.randint(0,10,(3,3))

array([[0, 7, 1],
       [7, 1, 7],
       [8, 7, 5]])

In [12]:
# normal ==> 배열을 정규분포로 값으로(평균 0, 표준편차 1의 (3,3)형태)
np.random.normal(0,1,(3,3))

array([[-0.74481489, -0.4650855 , -0.23470946],
       [ 0.19310086, -0.24086008,  1.42451987],
       [-0.58502933, -0.78903011,  0.6014881 ]])

In [13]:
# seed ==> 재현성 문제를 해결(난수고정)
np.random.seed(0)

arr1 = np.random.randint(10,size=6)
arr2 = np.random.randint(10,size=(2,3))

print("arr1:\n%s" % arr1)
print("ndim: %d, shape: %s, size: %d, dtype: %s\n" % 
      (arr1.ndim, arr1.shape, arr1.size, arr1.dtype)) 
print("arr2:\n%s" % arr2)
print("ndim: %d, shape: %s, size: %d, dtype: %s" % 
      (arr2.ndim, arr2.shape, arr2.size, arr2.dtype)) 

arr1:
[5 0 3 3 7 9]
ndim: 1, shape: (6,), size: 6, dtype: int32

arr2:
[[3 5 2]
 [4 7 6]]
ndim: 2, shape: (2, 3), size: 6, dtype: int32


### 인덱싱(단일 원소의 접근하는 기법)

In [14]:
arr1

array([5, 0, 3, 3, 7, 9])

In [15]:
# 음수로 인덱싱도 가능
arr1[0], arr1[5], arr1[-6], arr1[-1]

(5, 9, 5, 9)

In [16]:
arr2

array([[3, 5, 2],
       [4, 7, 6]])

In [17]:
arr2[0,0], arr2[0,2], arr2[-1,-3], arr2[-1,-1]

(3, 2, 4, 6)

In [18]:
arr2[0,0]=9
arr2

array([[9, 5, 2],
       [4, 7, 6]])

### 슬라이싱(부분집합을 추출하는 기법)

In [19]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# 0부터 4까지 1칸씩
arr1[0:5:1]

array([0, 1, 2, 3, 4])

In [21]:
# 앞의 0과 step도 생략 가능
arr1[:5:1], arr1[:5:], arr1[:5]

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [22]:
# 중간자 생략하면 끝까지 라는 뜻
arr1[2:9:2], arr1[2::2]

(array([2, 4, 6, 8]), array([2, 4, 6, 8]))

In [23]:
# 거꾸로 출력
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
# -1부터 -10까지 거꾸로 출력
arr1[-1:-11:-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [25]:
# -5부터 거꾸로 끝까지 출력
arr1[-5::-1]

array([5, 4, 3, 2, 1, 0])

In [26]:
# reshape ==> 행과 열을 변환(-1은 정해지지 않았다는 뜻)
arr2 = np.arange(12).reshape(-1,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
# 전체 출력
arr2[:3,:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
arr2[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
arr2[:2,:3]

array([[0, 1, 2],
       [4, 5, 6]])

In [30]:
arr2[:2,2::-1]

array([[2, 1, 0],
       [6, 5, 4]])

In [31]:
# 행에 대해서는 슬라이싱, 열에 대해서는 인덱싱
arr2[1:,-1]

array([ 7, 11])

In [32]:
# 마지막 행에 대한 모든 열 출력
arr2[-1,:], arr2[-1]

(array([ 8,  9, 10, 11]), array([ 8,  9, 10, 11]))

### 연결

In [33]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

In [34]:
# list들을 연결하는 concatenate(연결할 list는 []안에)
np.concatenate([list1,list2])

array([1, 2, 3, 4, 5, 6])

In [35]:
# axis에서 0은 행으로 연결, 1은 열로 연결
arr1 = np.concatenate([list1,list2],axis=0)
arr1

array([1, 2, 3, 4, 5, 6])

### 구조 변환

In [36]:
arr2 = arr1.reshape(-1,3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# 행으로 연결
np.concatenate([arr2,arr2],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
# 열로 연결
np.concatenate([arr2,arr2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [39]:
# vstack ==> 행으로 연결
np.vstack([arr2,arr2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
# hstack ==> 열로 연결
np.hstack([arr2,arr2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### 내장 함수(vectorize funtion => 빠름)

In [41]:
np.random.seed(0)

arr2 = np.random.randint(1,10,(3,4))
arr2

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [42]:
# axis 지정 안했으므로 모든 값 더함
np.sum(arr2), arr2.sum()

(65, 65)

In [43]:
# 행의 방향으로 더하기
np.sum(arr2,axis=0), arr2.sum(axis=0)

(array([19, 13, 17, 16]), array([19, 13, 17, 16]))

In [44]:
# 열의 방향으로 더하기
np.sum(arr2,axis=1), arr2.sum(axis=1)

(array([15, 21, 29]), array([15, 21, 29]))

In [45]:
np.min(arr2, axis=0), np.max(arr2, axis=0)

(array([5, 1, 4, 3]), array([8, 8, 7, 9]))

In [46]:
arr2.min(axis=0), arr2.max(axis=0)

(array([5, 1, 4, 3]), array([8, 8, 7, 9]))

### 브로드캐스팅(행열 구조를 동일하게 맞춰줌)

In [47]:
np.random.seed(0)

X = np.random.random((10, 3))
X

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194]])

In [48]:
# 10행3열 -> 1행3열
Xmean = X.mean(axis=0)
Xmean

array([0.52101579, 0.62614181, 0.59620338])

In [49]:
# 10행3열 - 1행3열(연상을 위해 브로드캐스팅으로 구조 맞춤)
Xcentered = X - Xmean
Xcentered

array([[ 0.02779771,  0.08904756,  0.00655999],
       [ 0.02386739, -0.20248701,  0.04969073],
       [-0.08342858,  0.26563119,  0.36745938],
       [-0.13757427,  0.16558323, -0.06730846],
       [ 0.04702877,  0.29945483, -0.52516732],
       [-0.43388649, -0.60592341,  0.23641646],
       [ 0.25714096,  0.24387034,  0.38241496],
       [ 0.27814277, -0.16466245,  0.18432579],
       [-0.40274137,  0.01377921, -0.45285009],
       [ 0.42365312, -0.10429349, -0.18154144]])

### 부울 배열과 마스킹 연산

In [50]:
np.random.seed(0)

X = np.random.randint(1, 10, size=(3, 4))
X

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [51]:
(X > 5) & (X < 8)

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False,  True, False]])

In [52]:
# True가 나오는 개수(and 연산자)
np.sum((X > 5) & (X < 8))

3

In [53]:
# True가 나오는 개수(or 연산자)
np.sum((X > 5) | (X < 8))

12

In [54]:
# 행의 방향으로
np.sum((X > 5) & (X < 8), axis=0)

array([1, 0, 2, 0])

In [55]:
# 열의 방향으로
np.sum((X > 5) & (X < 8), axis=1)

array([1, 1, 1])

In [56]:
X[(X > 5) & (X < 8)]

array([6, 6, 7])

### 팬시 인덱싱(인덱스를 담고 있는 배열)

In [57]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])

In [59]:
# row로 X의 행 인덱싱
X[row]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
# col로 X의 열 인덱싱
X[:, col]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [61]:
X[row, col]

array([ 1,  6, 11])

In [62]:
X[row.reshape(-1, 1), col]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

### 복합 인덱싱

In [63]:
X = np.zeros(12).reshape((3, 4))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
X[1,0]=1
X

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
# [1,3] -> 팬시 인덱싱
X[1, [1, 3]] = 1
X

array([[0., 0., 0., 0.],
       [1., 1., 0., 1.],
       [0., 0., 0., 0.]])

In [66]:
# 행과 열 팬시 인덱싱
X[[0, 2], [1, 3]] = 2
X

array([[0., 2., 0., 0.],
       [1., 1., 0., 1.],
       [0., 0., 0., 2.]])

In [67]:
# 행 슬라이싱 + 열 팬시 인덱싱
X[0:3, [0, 2]] = 3
X

array([[3., 2., 3., 0.],
       [3., 1., 3., 1.],
       [3., 0., 3., 2.]])

### 정렬

In [68]:
np.random.seed(0)

x = np.array(np.random.randint(10, size=5))
x

array([5, 0, 3, 3, 7])

In [69]:
# sort ==> 오름차순으로 정렬
np.sort(x)

array([0, 3, 3, 5, 7])

In [70]:
x

array([5, 0, 3, 3, 7])

In [71]:
x.sort()
x

array([0, 3, 3, 5, 7])

In [72]:
np.random.seed(0)

x = np.array(np.random.randint(10, size=5))
x

array([5, 0, 3, 3, 7])

In [73]:
# argsort ==> sort된 인덱스를 전달
idx = np.argsort(x)
idx

array([1, 2, 3, 0, 4], dtype=int64)

In [74]:
# 팬시 인덱싱을 통한 정렬
x[idx]

array([0, 3, 3, 5, 7])